name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile Java Classes
      run: |
        find src -name "*.java" > sources.txt
        javac @sources.txt -d out

    - name: Run Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/latest/download/checkstyle-10.3.jar -O checkstyle.jar
        java -jar checkstyle.jar -c /googlecheckstyle.xml src/**/*.java || exit 1

    - name: Run Tests
      run: |
        cd out
        java Main || exit 1
