name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile Java Classes
      run: |
        find src -name "*.java" > sources.txt
        javac @sources.txt -d out

    - name: Run Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/latest/download/checkstyle-10.18.1-all.jar -O checkstyle.jar
        wget https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml -O google_checks.xml
        java -jar checkstyle.jar -c google_checks.xml $(find src -name "*.java")  exit 1

    - name: Run Tests
      run: |
        cd out
        java Main  exit 1