name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile Java Classes
      run: javac src/*.java -d out

    - name: Run Checkstyle
      run: |
        wget https://checkstyle.sourceforge.io/cmdline.html -O checkstyle.jar
        java -jar checkstyle.jar -c /googlecheckstyle.xml src/*.java

    - name: Run Tests
      run: |
        cd out
        java Main
